import StyleDictionary from 'style-dictionary';

// ─── HELPERS ─────────────────────────────────────────────────────────────────

// Find the --ds-* segment in a token's path (the actual token key from the JSON).
function getDsSegment(token) {
  return token.path.find((p) => typeof p === 'string' && p.startsWith('--ds-')) ?? null;
}

// Typography "label" tokens like --ds-typography-display-xlarge: "display-xlarge"
// are internal Figma names with no CSS meaning. Exclude everything except -font-family.
function isTypographyLabel(token, usesDtcg) {
  const type = usesDtcg ? token.$type : token.type;
  if (type !== 'string') return false;
  const seg = getDsSegment(token);
  return seg !== null && !seg.endsWith('-font-family');
}

function getVal(token, usesDtcg) {
  return usesDtcg ? token.$value : token.value;
}

function getType(token, usesDtcg) {
  return usesDtcg ? token.$type : token.type;
}

// Numeric tokens get px — except font-weight, which is always unitless in CSS.
function toPx(val, seg = '') {
  if (typeof val !== 'number') return val;
  if (seg.includes('-font-weight')) return String(val);
  return `${val}px`;
}

// Convert RGBA hex (#RRGGBBAA) → Android ARGB hex (#AARRGGBB).
function toAndroidColor(hex) {
  if (/^#[0-9a-fA-F]{8}$/.test(hex)) {
    return `#${hex.slice(7, 9)}${hex.slice(1, 7)}`.toUpperCase();
  }
  return hex.toUpperCase();
}

// Only output tokens that came from a source file (not from primitives.json include).
function isSource(token) {
  return token.isSource === true;
}

// ─── CSS FORMAT ──────────────────────────────────────────────────────────────

function buildCssFormat({ dictionary, options }) {
  const usesDtcg = options.usesDtcg ?? false;

  const tokens = dictionary.allTokens.filter(
    (t) => isSource(t) && !isTypographyLabel(t, usesDtcg),
  );

  // color.json tokens sit under a Light / Dark wrapper group.
  // Everything else (spacing, typography, etc.) sits at the top level.
  const rootTokens = tokens.filter((t) => t.path[0] !== 'Dark');
  const darkTokens = tokens.filter((t) => t.path[0] === 'Dark');

  const toLine = (t) => {
    const type = getType(t, usesDtcg);
    const val = getVal(t, usesDtcg);
    const seg = getDsSegment(t) ?? '';
    const css = type === 'color' || type === 'string' ? val : toPx(val, seg);
    return `  --${t.name}: ${css};`;
  };

  return [
    '/* Desnify Foundations — generated by Style Dictionary. DO NOT EDIT. */',
    '',
    ':root {',
    rootTokens.map(toLine).join('\n'),
    '}',
    '',
    '[data-theme="dark"] {',
    darkTokens.map(toLine).join('\n'),
    '}',
    '',
  ].join('\n');
}

// ─── SWIFT FORMAT ────────────────────────────────────────────────────────────

function buildSwiftFormat({ dictionary, options }) {
  const usesDtcg = options.usesDtcg ?? false;

  const tokens = dictionary.allTokens.filter(
    (t) => isSource(t) && !isTypographyLabel(t, usesDtcg),
  );

  // Pair Light and Dark color tokens by their transformed name so we can
  // emit a single UIColor(dynamicProvider:) constant per semantic color.
  const colorPairs = {}; // { [name]: { light?: token, dark?: token } }
  const otherTokens = [];

  for (const token of tokens) {
    if (getType(token, usesDtcg) === 'color') {
      const slot = token.path[0] === 'Dark' ? 'dark' : 'light';
      colorPairs[token.name] ??= {};
      colorPairs[token.name][slot] = token;
    } else {
      otherTokens.push(token);
    }
  }

  const lines = [];

  for (const [name, { light, dark }] of Object.entries(colorPairs)) {
    const lv = light ? getVal(light, usesDtcg) : null;
    const dv = dark ? getVal(dark, usesDtcg) : null;
    if (lv && dv) {
      lines.push(
        `    static let ${name} = UIColor { tc in`,
        `        tc.userInterfaceStyle == .dark`,
        `            ? UIColor(hex: "${dv}")`,
        `            : UIColor(hex: "${lv}")`,
        `    }`,
      );
    } else {
      lines.push(`    static let ${name} = UIColor(hex: "${lv ?? dv}")`);
    }
  }

  for (const token of otherTokens) {
    const type = getType(token, usesDtcg);
    const val = getVal(token, usesDtcg);
    if (type === 'string') {
      lines.push(`    static let ${token.name}: String = "${val}"`);
    } else if (typeof val === 'number') {
      // px → pt is 1:1 for @1x / standard design exports.
      lines.push(`    static let ${token.name}: CGFloat = ${val}`);
    }
  }

  return [
    '// Desnify Foundations — generated by Style Dictionary. DO NOT EDIT.',
    'import UIKit',
    '',
    '// Hex string → UIColor. Supports #RGB, #RRGGBB, #RRGGBBAA.',
    'private extension UIColor {',
    '    convenience init(hex string: String) {',
    '        var hex = string.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)',
    '        var int: UInt64 = 0',
    '        Scanner(string: hex).scanHexInt64(&int)',
    '        let a, r, g, b: UInt64',
    '        switch hex.count {',
    '        case 6:  (a, r, g, b) = (255, int >> 16, int >> 8 & 0xFF, int & 0xFF)',
    '        case 8:  (a, r, g, b) = (int >> 24, int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF)',
    '        default: (a, r, g, b) = (255, 0, 0, 0)',
    '        }',
    '        self.init(',
    '            red: CGFloat(r) / 255,',
    '            green: CGFloat(g) / 255,',
    '            blue: CGFloat(b) / 255,',
    '            alpha: CGFloat(a) / 255',
    '        )',
    '    }',
    '}',
    '',
    'struct DS {',
    lines.join('\n'),
    '}',
    '',
  ].join('\n');
}

// ─── ANDROID XML FORMAT ──────────────────────────────────────────────────────

function buildAndroidXmlFormat(mode) {
  return function ({ dictionary, options }) {
    const usesDtcg = options.usesDtcg ?? false;
    const isNight = mode === 'night';

    const tokens = dictionary.allTokens.filter((t) => {
      if (!isSource(t)) return false;
      if (isTypographyLabel(t, usesDtcg)) return false;
      return isNight ? t.path[0] === 'Dark' : t.path[0] !== 'Dark';
    });

    // Pre-build name → resolved-value map so letter-spacing tokens can look up
    // their paired font-size without a second pass.
    const nameToVal = new Map(tokens.map((t) => [t.name, getVal(t, usesDtcg)]));

    const colorLines = [];
    const dimenLines = [];
    const floatLines = []; // em letter-spacing values — <item format="float">
    const intLines = [];
    const strLines = [];

    for (const token of tokens) {
      const type = getType(token, usesDtcg);
      const val = getVal(token, usesDtcg);
      const seg = getDsSegment(token) ?? '';

      if (type === 'color') {
        colorLines.push(`    <color name="${token.name}">${toAndroidColor(val)}</color>`);
      } else if (type === 'number' && typeof val === 'number') {
        if (seg.includes('-font-weight')) {
          // Font weight is dimensionless — use <integer>.
          intLines.push(`    <integer name="${token.name}">${val}</integer>`);
        } else if (seg.includes('-letter-spacing')) {
          // Android TextView.letterSpacing expects em units (a unitless float).
          // em = letter_spacing_px / font_size_px for this typography style.
          // <dimen> requires a CSS unit suffix, so we use <item format="float">.
          const fontSizeName = token.name.replace(/_letter_spacing$/, '_font_size');
          const fontSize = nameToVal.get(fontSizeName);
          const em =
            typeof fontSize === 'number' && fontSize !== 0
              ? Math.round((val / fontSize) * 10000) / 10000
              : val;
          floatLines.push(
            `    <item name="${token.name}" format="float" type="dimen">${em}</item>`,
          );
        } else if (seg.includes('-font-size')) {
          // Font sizes scale with user accessibility settings.
          dimenLines.push(`    <dimen name="${token.name}">${val}sp</dimen>`);
        } else {
          // Spacing, sizing, corner radius, border width, line-height.
          dimenLines.push(`    <dimen name="${token.name}">${val}dp</dimen>`);
        }
      } else if (type === 'string' && typeof val === 'string') {
        strLines.push(`    <string name="${token.name}" translatable="false">${val}</string>`);
      }
    }

    const modeLabel = isNight ? 'Dark' : 'Light';

    const sections = [];
    if (colorLines.length) sections.push(...colorLines);
    if (dimenLines.length) { if (sections.length) sections.push(''); sections.push(...dimenLines); }
    if (floatLines.length) { if (sections.length) sections.push(''); sections.push(...floatLines); }
    if (intLines.length)   { if (sections.length) sections.push(''); sections.push(...intLines); }
    if (strLines.length)   { if (sections.length) sections.push(''); sections.push(...strLines); }

    return [
      '<?xml version="1.0" encoding="utf-8"?>',
      `<!-- Desnify Foundations (${modeLabel} mode) — generated by Style Dictionary. DO NOT EDIT. -->`,
      `<!-- Night-mode colors belong in res/values-night/; light-mode in res/values/. -->`,
      '<resources>',
      ...sections,
      '</resources>',
      '',
    ].join('\n');
  };
}

// ─── STYLE DICTIONARY CONFIG ─────────────────────────────────────────────────

const sd = new StyleDictionary({
  // primitives.json supplies raw values for alias resolution only — not output.
  include: ['tokens/primitives.json'],

  // Semantic token files are what gets transformed into platform outputs.
  source: [
    'tokens/color.json',
    'tokens/spacing.json',
    'tokens/typography.json',
    'tokens/border.json',
    'tokens/corner-radius.json',
    'tokens/width.json',
    'tokens/height.json',
  ],

  hooks: {
    transforms: {
      // CSS: strip the leading -- so the CSS formatter can prepend it correctly.
      // e.g. ["Light", "Foreground", "--ds-color-fg-brand-primary"] → "ds-color-fg-brand-primary"
      //      ["--ds-spacing-12"]                                     → "ds-spacing-12"
      'name/ds/css': {
        type: 'name',
        transform(token) {
          const seg = getDsSegment(token);
          return seg ? seg.slice(2) : token.path.join('-').toLowerCase();
        },
      },

      // Swift: strip --ds- prefix, camelCase the rest.
      // e.g. "--ds-color-fg-brand-primary" → "colorFgBrandPrimary"
      'name/ds/swift': {
        type: 'name',
        transform(token) {
          const seg = getDsSegment(token);
          const base = seg ? seg.slice('--ds-'.length) : token.path.join('-').toLowerCase();
          return base.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
        },
      },

      // Android: strip leading --, replace hyphens with underscores.
      // e.g. "--ds-spacing-12" → "ds_spacing_12"
      'name/ds/android': {
        type: 'name',
        transform(token) {
          const seg = getDsSegment(token);
          const base = seg ? seg.slice(2) : token.path.join('-').toLowerCase();
          return base.replace(/-/g, '_');
        },
      },
    },

    formats: {
      'css/ds-tokens': buildCssFormat,
      'swift/ds-tokens': buildSwiftFormat,
      'android/ds-tokens': buildAndroidXmlFormat('light'),
      'android/ds-tokens-night': buildAndroidXmlFormat('night'),
    },
  },

  platforms: {
    web: {
      transforms: ['name/ds/css'],
      buildPath: 'dist/web/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/ds-tokens',
        },
      ],
    },

    ios: {
      transforms: ['name/ds/swift'],
      buildPath: 'dist/ios/',
      files: [
        {
          destination: 'DesignTokens.swift',
          format: 'swift/ds-tokens',
        },
      ],
    },

    android: {
      transforms: ['name/ds/android'],
      buildPath: 'dist/android/',
      files: [
        {
          // Light mode → place in res/values/tokens.xml
          destination: 'tokens.xml',
          format: 'android/ds-tokens',
        },
        {
          // Dark mode → place in res/values-night/tokens.xml
          destination: 'tokens-night.xml',
          format: 'android/ds-tokens-night',
        },
      ],
    },
  },
});

await sd.buildAllPlatforms();
